language: android
jdk: oraclejdk8
sudo: false
env:
  global:
  - ANDROID_API_LEVEL=26
  - EMULATOR_API_LEVEL=24
  - ANDROID_BUILD_TOOLS_VERSION=26.0.2
android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-$ANDROID_BUILD_TOOLS_VERSION
  - android-$ANDROID_API_LEVEL
  - android-$EMULATOR_API_LEVEL
  - extra-google-google_play_services
  - extra-android-support
  - addon-google_apis-google-$ANDROID_API_LEVEL
  - addon-google_apis-google-$EMULATOR_API_LEVEL
  - extra-android-support
  - extra-android-m2repository
  - extra-google-m2repository
script:
- "./gradlew clean assembleDebug"
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache"
notifications:
  slack:
    rooms:
      secure: WELNcQr65i59DsdzAbT+u8CkDBRWzLSRqWXR2FocLJP1Hre85M3u/CDfRl1lUsN3k5gtKc3FbRWxPVRHSnAObOIrxUH7aIDsvhuc2hW3CWhrAX1IOujTNcD48UrRQambAqDookm5b1M9xgQwoq5+6GWmg+DLfJjygnmgpF0Wk8OrKK9ifnvp9dJlDP8ketyokc4J/uOXbsm0IuSD9R8K9auyDlXC0DJRG0tuQrc1kjFW/N2yfxRlwUyP32wTLKaiaMAbJejIiZV4pHXR9kRiSVW47pUlesL91HrtwzRrsWhqeZfHb8iw+4Lt1rHmRLx0LkWBbMZTw2jplfFkjTARLR/eHPK61Zn8GR7+B1yfxtesqmtCVyH8Qt4QLCga+ZzRZNKBe8Dio/aYtQHc/UCfxvUDoYy/j/d6EPqYipjlUYEA09Cy/b/uUv4B9vl5cqLiVBIJrHo+9bYUvdvn9zMZHmkK0JoOYRVWJGOkXWOBhQaCP510xRnGQQEh+bYsQXTTica7aWnhRNTi+K4uO1v/PJPkQBpVD9YtufmVYy598gjDPhU291CFxOnmIy5IG9WxIorBMDW8h986pUTqvr7nREbyxosGxQolLCZ+yyLmsU1K4NMIAWUO8DXkP/gUyLVIIfkESHPi55k6V/6+hM0h9ocL660pyvUSLosZLOtInME=
    on_success: always
    on_failure: always
branches:
  only:
    - master